### ISSUE TITLE
prusa connect only reacts on manual refresh

### ISSUE THREAD

**Issue by kiltraw** [mozgy/esp32-cam#2]
thanks for the great work first!
i got a xiao sense setup. seems everything worked quite fine, i got the prusa connect registered, can adjust and view the webstream, but the camera picture in prusa connect only ever changes when i type 192.169.1.xxx:8080/prusa in my browser and let it push the pic there manually.

**Comment by mozgy** [comment]
Change this
https://github.com/mozgy/esp32-cam/blob/cb0695d871d322084fbb5e68c695b6a417713f91/include/variables.h#L21
to #define and recompile ..

**Comment by kiltraw** [comment]
thank you! solved it!
